char	EndText[87][32]={
"                                ",
"        Congratulations!        ",
"                                ",

" Prospecting down Surbiton way  ",
"    was not such a bad idea     ",
"          after all.            ",

"   All that hard work really    ",
"           paid off.            ",
"                                ",

"Willy now has so much money that",
" he has no idea what to do with ",
"            it all.             ",

"                                ",
"      Have you any ideas ?      ",
"                                ",

"                                ",
"        Manic Miner PC          ",
"                                ",

"  Based on an original idea by  ",
"         Matthew Smith          ",
"                                ",

"    Programming and Graphics    ",
"          Andy Noble            ",
"                                ",

"        Music Arrangement       ",
"          Matt Simmonds         ",
"                                ",

"'Tales from a Parallel Universe'",
"          Level Design          ",
"       Lee 'BLOOD!' Tonks       ",

"       Testing and Ideas        ",
"         Ewan Christie          ",
"                                ",

"   'Bad Guy' Data Extraction    ",
"      Tyrone L. Cartwright      ",
"                                ",

"   MIDAS Digital Audio System   ",
"         Sahara Surfers         ",
"                                ",

"            PMODE/W             ",
"       Charles Scheffold        ",
"          Thomas Pytel          ",

"     A BIG Thank You to the     ",
"        following people        ",
"                                ",

"         David H. Tolley        ",
"   For the constant slagging's  ",
"                                ",

"          Phil M. Brown         ",
"         For the Pizza's        ",
"                                ",

"     Derek 'Anti-Alias' Ham     ",
"      For making me laugh       ",
"                                ",

"       Luise Etherington        ",
"  For the Lasagna and the Sofa  ",
"                                ",

"  John Carlisle & Dave Sowerby  ",
"       'The Geordy Boys'        ",
"                                ",

"         Nikkie Claxton         ",
"  For putting up with me never  ",
"     getting back in touch      ",

"         Gerton Lunter          ",
"     For the excellent Z80      ",
"                                ",

"          James McKay           ",
"     For the excellent X128     ",
"                                ",

"        Arsen Torbarina         ",
"   For the JSW Fan Club Page    ",
"                                ",

"          Damien Burk           ",
"   My first ever Speccy page    ",
"                                ",

"        All the guys on         ",
"       COMP.SYS.SINCLAIR        ",
"                                ",

"Everybody who wrote to me giving",
"    encouragement and advice    ",
"                                ",

"           Cheat Mode           ",
"           For 802926           ",
"                                ",

" Open Dingux version : Alekmaul ",
"     (c)1997 Andy Noble         ",
"                                "
};

WORD	EndPause[87]={
	100,0,0,
	200,0,0,
	150,0,0,
	250,0,0,
	100,0,0,
	 60,0,0,
	100,0,0,

	100,0,0,
	100,0,0,
	100,0,0,
	100,0,0,
	100,0,0,
	100,0,0,
	100,0,0,

	100,0,0,

	 50,0,0,
	 50,0,0,
	 50,0,0,
	 50,0,0,
	 50,0,0,
	 50,0,0,
	 50,0,0,
	 50,0,0,
	 50,0,0,
	 50,0,0,
	 50,0,0,
	 100,0,0,

	 50,0,0,

	 300,0,0};


